[package]
name = "leetcode"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "test"
path = "src/39-47.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

